apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prom
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Timescale
    type: postgres
    uid: timescale
    access: proxy
    url: timescaledb:5432
    database: iot
    user: iot
    secureJsonData:
      password: iot
    jsonData:
      sslmode: disable
      timescaledb: true
    editable: true
